apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ceph-objectstore-broker
  labels:
    app: cosb
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: cosb
    spec:
      containers:
      - name: cosb
        imagePullPolicy: Always
        image: bloeys/ceph-objectstore-broker:1
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: cosb-env
        